// <auto-generated />
using System;
using FA22.P03.Web.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FA22.P03.Web.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20220907023042_seeded-data")]
    partial class seededdata
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("FA22.P03.Web.Features.ItemListings.ItemListing", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("ItemId")
                        .HasColumnType("int");

                    b.Property<int?>("ListingId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.HasIndex("ListingId");

                    b.ToTable("ItemListings");
                });

            modelBuilder.Entity("FA22.P03.Web.Features.Items.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Condition")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ProductId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("FA22.P03.Web.Features.Listings.Listing", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("EndUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTimeOffset>("StartUtc")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.ToTable("Listings");
                });

            modelBuilder.Entity("FA22.P03.Web.Features.Products.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Super Nintendo (SNES) System. Mint Condition",
                            Name = "Super Mario World",
                            Price = 259.99m
                        },
                        new
                        {
                            Id = 2,
                            Description = "Moderate Condition Donkey Kong 64 cartridge for the Nintendo 64",
                            Name = "Donkey Kong 64",
                            Price = 199m
                        },
                        new
                        {
                            Id = 3,
                            Description = "Good condition with all 5 CDs, booklets, and material from original",
                            Name = "Half-Life 2: Collector's Edition",
                            Price = 559.99m
                        });
                });

            modelBuilder.Entity("FA22.P03.Web.Features.ItemListings.ItemListing", b =>
                {
                    b.HasOne("FA22.P03.Web.Features.Items.Item", "Item")
                        .WithMany("ItemListings")
                        .HasForeignKey("ItemId");

                    b.HasOne("FA22.P03.Web.Features.Listings.Listing", "Listing")
                        .WithMany("ItemsForSale")
                        .HasForeignKey("ListingId");

                    b.Navigation("Item");

                    b.Navigation("Listing");
                });

            modelBuilder.Entity("FA22.P03.Web.Features.Items.Item", b =>
                {
                    b.HasOne("FA22.P03.Web.Features.Products.Product", "Product")
                        .WithMany("Items")
                        .HasForeignKey("ProductId");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("FA22.P03.Web.Features.Items.Item", b =>
                {
                    b.Navigation("ItemListings");
                });

            modelBuilder.Entity("FA22.P03.Web.Features.Listings.Listing", b =>
                {
                    b.Navigation("ItemsForSale");
                });

            modelBuilder.Entity("FA22.P03.Web.Features.Products.Product", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
